# adapted from https://github.com/purcell/package-lint/blob/master/.github/workflows/test.yml
name: org-ref

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 29.4
          - 30.1
          - snapshot

    steps:
    - uses: actions/checkout@v4

    - uses: purcell/setup-emacs@v7.0
      with:
        version: ${{ matrix.emacs_version }}

    - name: Run tests
      run: make github-actions
